FROM selenium/standalone-firefox:latest
USER root
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN chmod -R a+rw /app
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - 
RUN apt-get install -y nodejs

RUN npm install -g smashtest

USER seluser